// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ciam-rebac/internal/conf"
	"ciam-rebac/internal/server"
	"ciam-rebac/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	relationshipsService := service.NewRelationshipsService(logger)
	healthService := service.NewHealthService()
	grpcServer := server.NewGRPCServer(confServer, relationshipsService, healthService, logger)
	httpServer := server.NewHTTPServer(confServer, relationshipsService, healthService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
