// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: kessel/relations/v1/health.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	KesselHealthService_GetLivez_FullMethodName  = "/kessel.relations.v1.KesselHealthService/GetLivez"
	KesselHealthService_GetReadyz_FullMethodName = "/kessel.relations.v1.KesselHealthService/GetReadyz"
)

// KesselHealthServiceClient is the client API for KesselHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KesselHealthServiceClient interface {
	GetLivez(ctx context.Context, in *GetLivezRequest, opts ...grpc.CallOption) (*GetLivezResponse, error)
	GetReadyz(ctx context.Context, in *GetReadyzRequest, opts ...grpc.CallOption) (*GetReadyzResponse, error)
}

type kesselHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKesselHealthServiceClient(cc grpc.ClientConnInterface) KesselHealthServiceClient {
	return &kesselHealthServiceClient{cc}
}

func (c *kesselHealthServiceClient) GetLivez(ctx context.Context, in *GetLivezRequest, opts ...grpc.CallOption) (*GetLivezResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLivezResponse)
	err := c.cc.Invoke(ctx, KesselHealthService_GetLivez_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kesselHealthServiceClient) GetReadyz(ctx context.Context, in *GetReadyzRequest, opts ...grpc.CallOption) (*GetReadyzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadyzResponse)
	err := c.cc.Invoke(ctx, KesselHealthService_GetReadyz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KesselHealthServiceServer is the server API for KesselHealthService service.
// All implementations must embed UnimplementedKesselHealthServiceServer
// for forward compatibility
type KesselHealthServiceServer interface {
	GetLivez(context.Context, *GetLivezRequest) (*GetLivezResponse, error)
	GetReadyz(context.Context, *GetReadyzRequest) (*GetReadyzResponse, error)
	mustEmbedUnimplementedKesselHealthServiceServer()
}

// UnimplementedKesselHealthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKesselHealthServiceServer struct {
}

func (UnimplementedKesselHealthServiceServer) GetLivez(context.Context, *GetLivezRequest) (*GetLivezResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLivez not implemented")
}
func (UnimplementedKesselHealthServiceServer) GetReadyz(context.Context, *GetReadyzRequest) (*GetReadyzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReadyz not implemented")
}
func (UnimplementedKesselHealthServiceServer) mustEmbedUnimplementedKesselHealthServiceServer() {}

// UnsafeKesselHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KesselHealthServiceServer will
// result in compilation errors.
type UnsafeKesselHealthServiceServer interface {
	mustEmbedUnimplementedKesselHealthServiceServer()
}

func RegisterKesselHealthServiceServer(s grpc.ServiceRegistrar, srv KesselHealthServiceServer) {
	s.RegisterService(&KesselHealthService_ServiceDesc, srv)
}

func _KesselHealthService_GetLivez_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLivezRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KesselHealthServiceServer).GetLivez(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KesselHealthService_GetLivez_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KesselHealthServiceServer).GetLivez(ctx, req.(*GetLivezRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KesselHealthService_GetReadyz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadyzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KesselHealthServiceServer).GetReadyz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KesselHealthService_GetReadyz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KesselHealthServiceServer).GetReadyz(ctx, req.(*GetReadyzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KesselHealthService_ServiceDesc is the grpc.ServiceDesc for KesselHealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KesselHealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kessel.relations.v1.KesselHealthService",
	HandlerType: (*KesselHealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLivez",
			Handler:    _KesselHealthService_GetLivez_Handler,
		},
		{
			MethodName: "GetReadyz",
			Handler:    _KesselHealthService_GetReadyz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kessel/relations/v1/health.proto",
}
