// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: kessel/relations/v1/health.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLivezRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLivezRequest) Reset() {
	*x = GetLivezRequest{}
	mi := &file_kessel_relations_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLivezRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLivezRequest) ProtoMessage() {}

func (x *GetLivezRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLivezRequest.ProtoReflect.Descriptor instead.
func (*GetLivezRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1_health_proto_rawDescGZIP(), []int{0}
}

type GetLivezResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLivezResponse) Reset() {
	*x = GetLivezResponse{}
	mi := &file_kessel_relations_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLivezResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLivezResponse) ProtoMessage() {}

func (x *GetLivezResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLivezResponse.ProtoReflect.Descriptor instead.
func (*GetLivezResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *GetLivezResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetLivezResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetReadyzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadyzRequest) Reset() {
	*x = GetReadyzRequest{}
	mi := &file_kessel_relations_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadyzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadyzRequest) ProtoMessage() {}

func (x *GetReadyzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadyzRequest.ProtoReflect.Descriptor instead.
func (*GetReadyzRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1_health_proto_rawDescGZIP(), []int{2}
}

type GetReadyzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadyzResponse) Reset() {
	*x = GetReadyzResponse{}
	mi := &file_kessel_relations_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadyzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadyzResponse) ProtoMessage() {}

func (x *GetReadyzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadyzResponse.ProtoReflect.Descriptor instead.
func (*GetReadyzResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1_health_proto_rawDescGZIP(), []int{3}
}

func (x *GetReadyzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetReadyzResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_kessel_relations_v1_health_proto protoreflect.FileDescriptor

const file_kessel_relations_v1_health_proto_rawDesc = "" +
	"\n" +
	" kessel/relations/v1/health.proto\x12\x13kessel.relations.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fGetLivezRequest\">\n" +
	"\x10GetLivezResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\"\x12\n" +
	"\x10GetReadyzRequest\"?\n" +
	"\x11GetReadyzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code2\xf4\x01\n" +
	"\x1cKesselRelationsHealthService\x12g\n" +
	"\bGetLivez\x12$.kessel.relations.v1.GetLivezRequest\x1a%.kessel.relations.v1.GetLivezResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/livez\x12k\n" +
	"\tGetReadyz\x12%.kessel.relations.v1.GetReadyzRequest\x1a&.kessel.relations.v1.GetReadyzResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/readyzBh\n" +
	"#org.project_kessel.api.relations.v1P\x01Z?github.com/project-kessel/relations-api/api/kessel/relations/v1b\x06proto3"

var (
	file_kessel_relations_v1_health_proto_rawDescOnce sync.Once
	file_kessel_relations_v1_health_proto_rawDescData []byte
)

func file_kessel_relations_v1_health_proto_rawDescGZIP() []byte {
	file_kessel_relations_v1_health_proto_rawDescOnce.Do(func() {
		file_kessel_relations_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_relations_v1_health_proto_rawDesc), len(file_kessel_relations_v1_health_proto_rawDesc)))
	})
	return file_kessel_relations_v1_health_proto_rawDescData
}

var file_kessel_relations_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kessel_relations_v1_health_proto_goTypes = []any{
	(*GetLivezRequest)(nil),   // 0: kessel.relations.v1.GetLivezRequest
	(*GetLivezResponse)(nil),  // 1: kessel.relations.v1.GetLivezResponse
	(*GetReadyzRequest)(nil),  // 2: kessel.relations.v1.GetReadyzRequest
	(*GetReadyzResponse)(nil), // 3: kessel.relations.v1.GetReadyzResponse
}
var file_kessel_relations_v1_health_proto_depIdxs = []int32{
	0, // 0: kessel.relations.v1.KesselRelationsHealthService.GetLivez:input_type -> kessel.relations.v1.GetLivezRequest
	2, // 1: kessel.relations.v1.KesselRelationsHealthService.GetReadyz:input_type -> kessel.relations.v1.GetReadyzRequest
	1, // 2: kessel.relations.v1.KesselRelationsHealthService.GetLivez:output_type -> kessel.relations.v1.GetLivezResponse
	3, // 3: kessel.relations.v1.KesselRelationsHealthService.GetReadyz:output_type -> kessel.relations.v1.GetReadyzResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_relations_v1_health_proto_init() }
func file_kessel_relations_v1_health_proto_init() {
	if File_kessel_relations_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_relations_v1_health_proto_rawDesc), len(file_kessel_relations_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kessel_relations_v1_health_proto_goTypes,
		DependencyIndexes: file_kessel_relations_v1_health_proto_depIdxs,
		MessageInfos:      file_kessel_relations_v1_health_proto_msgTypes,
	}.Build()
	File_kessel_relations_v1_health_proto = out.File
	file_kessel_relations_v1_health_proto_goTypes = nil
	file_kessel_relations_v1_health_proto_depIdxs = nil
}
