services:
  relations-api:
    image: "quay.io/cloudservices/kessel-relations:latest"
    environment:
      - "SPICEDB_PRESHARED=${SPICEDB_GRPC_PRESHARED_KEY}"
      # - "SPICEDB_PRESHARED_FILE=/run/secrets/spicedb_pre_shared"
      - "SPICEDB_ENDPOINT=spicedb:50051"
    build:
      dockerfile: Dockerfile
    profiles: ["relations-api"]
    secrets:
      - spicedb_pre_shared
    restart: "always"
    ports:
      - "8000:8000"
      - "9000:9000"


  spicedb:
    image: "authzed/spicedb"
    command: "serve"
    restart: "always"
    configs:
      - bootstrap_file
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=${SPICEDB_GRPC_PRESHARED_KEY}"
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_BOOTSTRAP_FILES=/bootstrap_file"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/spicedb?sslmode=disable"
    depends_on:
      - "migrate"

  migrate:
    image: "authzed/spicedb"
    command: "migrate head"
    restart: "on-failure"
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/spicedb?sslmode=disable"
    depends_on:
      - "database"

  database:
    image: "postgres"
    command: -c track_commit_timestamp=on
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"

configs:
  spicedb_pre_shared:
    environment: "SPICEDB_GRPC_PRESHARED_KEY"
  bootstrap_file:
    file: ./deploy/schema.yaml

secrets:
  spicedb_pre_shared:
    file: ./.secrets/local-spicedb-secret