// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/project-kessel/relations-api/internal/biz"
	"github.com/project-kessel/relations-api/internal/conf"
	"github.com/project-kessel/relations-api/internal/data"
	"github.com/project-kessel/relations-api/internal/server"
	"github.com/project-kessel/relations-api/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	spiceDbRepository, cleanup, err := data.NewSpiceDbRepository(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	createRelationshipsUsecase := biz.NewCreateRelationshipsUsecase(spiceDbRepository, logger)
	readRelationshipsUsecase := biz.NewReadRelationshipsUsecase(spiceDbRepository, logger)
	deleteRelationshipsUsecase := biz.NewDeleteRelationshipsUsecase(spiceDbRepository, logger)
	importBulkTuplesUsecase := biz.NewImportBulkTuplesUsecase(spiceDbRepository, logger)
	acquireLockUsecase := biz.NewAcquireLockUsecase(spiceDbRepository, logger)
	relationshipsService := service.NewRelationshipsService(logger, createRelationshipsUsecase, readRelationshipsUsecase, deleteRelationshipsUsecase, importBulkTuplesUsecase, acquireLockUsecase)
	isBackendAvaliableUsecase := biz.NewIsBackendAvailableUsecase(spiceDbRepository)
	healthService := service.NewHealthService(isBackendAvaliableUsecase)
	checkUsecase := biz.NewCheckUsecase(spiceDbRepository, logger)
	checkForUpdateUsecase := biz.NewCheckForUpdateUsecase(spiceDbRepository, logger)
	checkBulkUsecase := biz.NewCheckBulkUsecase(spiceDbRepository, logger)
	checkService := service.NewCheckService(logger, checkUsecase, checkForUpdateUsecase, checkBulkUsecase)
	getSubjectsUsecase := biz.NewGetSubjectsUseCase(spiceDbRepository)
	getResourcesUsecase := biz.NewGetResourcesUseCase(spiceDbRepository)
	lookupService := service.NewLookupService(logger, getSubjectsUsecase, getResourcesUsecase)
	meterProvider, err := server.NewMeterProvider(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	meter, err := server.NewMeter(confServer, meterProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer, err := server.NewGRPCServer(confServer, relationshipsService, healthService, checkService, lookupService, meter, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer, err := server.NewHTTPServer(confServer, relationshipsService, healthService, checkService, lookupService, meter, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
