// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: kessel/relations/v1beta1/check.proto

package v1beta1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckResponse_Allowed int32

const (
	CheckResponse_ALLOWED_UNSPECIFIED CheckResponse_Allowed = 0
	CheckResponse_ALLOWED_TRUE        CheckResponse_Allowed = 1
	CheckResponse_ALLOWED_FALSE       CheckResponse_Allowed = 2 // e.g.  ALLOWED_CONDITIONAL = 3;
)

// Enum value maps for CheckResponse_Allowed.
var (
	CheckResponse_Allowed_name = map[int32]string{
		0: "ALLOWED_UNSPECIFIED",
		1: "ALLOWED_TRUE",
		2: "ALLOWED_FALSE",
	}
	CheckResponse_Allowed_value = map[string]int32{
		"ALLOWED_UNSPECIFIED": 0,
		"ALLOWED_TRUE":        1,
		"ALLOWED_FALSE":       2,
	}
)

func (x CheckResponse_Allowed) Enum() *CheckResponse_Allowed {
	p := new(CheckResponse_Allowed)
	*p = x
	return p
}

func (x CheckResponse_Allowed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckResponse_Allowed) Descriptor() protoreflect.EnumDescriptor {
	return file_kessel_relations_v1beta1_check_proto_enumTypes[0].Descriptor()
}

func (CheckResponse_Allowed) Type() protoreflect.EnumType {
	return &file_kessel_relations_v1beta1_check_proto_enumTypes[0]
}

func (x CheckResponse_Allowed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckResponse_Allowed.Descriptor instead.
func (CheckResponse_Allowed) EnumDescriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{1, 0}
}

type CheckForUpdateResponse_Allowed int32

const (
	CheckForUpdateResponse_ALLOWED_UNSPECIFIED CheckForUpdateResponse_Allowed = 0
	CheckForUpdateResponse_ALLOWED_TRUE        CheckForUpdateResponse_Allowed = 1
	CheckForUpdateResponse_ALLOWED_FALSE       CheckForUpdateResponse_Allowed = 2 // e.g.  ALLOWED_CONDITIONAL = 3;
)

// Enum value maps for CheckForUpdateResponse_Allowed.
var (
	CheckForUpdateResponse_Allowed_name = map[int32]string{
		0: "ALLOWED_UNSPECIFIED",
		1: "ALLOWED_TRUE",
		2: "ALLOWED_FALSE",
	}
	CheckForUpdateResponse_Allowed_value = map[string]int32{
		"ALLOWED_UNSPECIFIED": 0,
		"ALLOWED_TRUE":        1,
		"ALLOWED_FALSE":       2,
	}
)

func (x CheckForUpdateResponse_Allowed) Enum() *CheckForUpdateResponse_Allowed {
	p := new(CheckForUpdateResponse_Allowed)
	*p = x
	return p
}

func (x CheckForUpdateResponse_Allowed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckForUpdateResponse_Allowed) Descriptor() protoreflect.EnumDescriptor {
	return file_kessel_relations_v1beta1_check_proto_enumTypes[1].Descriptor()
}

func (CheckForUpdateResponse_Allowed) Type() protoreflect.EnumType {
	return &file_kessel_relations_v1beta1_check_proto_enumTypes[1]
}

func (x CheckForUpdateResponse_Allowed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckForUpdateResponse_Allowed.Descriptor instead.
func (CheckForUpdateResponse_Allowed) EnumDescriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{3, 0}
}

type CheckBulkResponseItem_Allowed int32

const (
	CheckBulkResponseItem_ALLOWED_UNSPECIFIED CheckBulkResponseItem_Allowed = 0
	CheckBulkResponseItem_ALLOWED_TRUE        CheckBulkResponseItem_Allowed = 1
	CheckBulkResponseItem_ALLOWED_FALSE       CheckBulkResponseItem_Allowed = 2 // e.g.  ALLOWED_CONDITIONAL = 3;
)

// Enum value maps for CheckBulkResponseItem_Allowed.
var (
	CheckBulkResponseItem_Allowed_name = map[int32]string{
		0: "ALLOWED_UNSPECIFIED",
		1: "ALLOWED_TRUE",
		2: "ALLOWED_FALSE",
	}
	CheckBulkResponseItem_Allowed_value = map[string]int32{
		"ALLOWED_UNSPECIFIED": 0,
		"ALLOWED_TRUE":        1,
		"ALLOWED_FALSE":       2,
	}
)

func (x CheckBulkResponseItem_Allowed) Enum() *CheckBulkResponseItem_Allowed {
	p := new(CheckBulkResponseItem_Allowed)
	*p = x
	return p
}

func (x CheckBulkResponseItem_Allowed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckBulkResponseItem_Allowed) Descriptor() protoreflect.EnumDescriptor {
	return file_kessel_relations_v1beta1_check_proto_enumTypes[2].Descriptor()
}

func (CheckBulkResponseItem_Allowed) Type() protoreflect.EnumType {
	return &file_kessel_relations_v1beta1_check_proto_enumTypes[2]
}

func (x CheckBulkResponseItem_Allowed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckBulkResponseItem_Allowed.Descriptor instead.
func (CheckBulkResponseItem_Allowed) EnumDescriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{5, 0}
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ObjectReference       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Consistency   *Consistency           `protobuf:"bytes,4,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CheckRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

type CheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          CheckResponse_Allowed  `protobuf:"varint,1,opt,name=allowed,proto3,enum=kessel.relations.v1beta1.CheckResponse_Allowed" json:"allowed,omitempty"`
	ConsistencyToken *ConsistencyToken      `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() CheckResponse_Allowed {
	if x != nil {
		return x.Allowed
	}
	return CheckResponse_ALLOWED_UNSPECIFIED
}

func (x *CheckResponse) GetConsistencyToken() *ConsistencyToken {
	if x != nil {
		return x.ConsistencyToken
	}
	return nil
}

type CheckForUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ObjectReference       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdateRequest) Reset() {
	*x = CheckForUpdateRequest{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdateRequest) ProtoMessage() {}

func (x *CheckForUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckForUpdateRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{2}
}

func (x *CheckForUpdateRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckForUpdateRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckForUpdateRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type CheckForUpdateResponse struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Allowed          CheckForUpdateResponse_Allowed `protobuf:"varint,1,opt,name=allowed,proto3,enum=kessel.relations.v1beta1.CheckForUpdateResponse_Allowed" json:"allowed,omitempty"`
	ConsistencyToken *ConsistencyToken              `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckForUpdateResponse) Reset() {
	*x = CheckForUpdateResponse{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdateResponse) ProtoMessage() {}

func (x *CheckForUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckForUpdateResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{3}
}

func (x *CheckForUpdateResponse) GetAllowed() CheckForUpdateResponse_Allowed {
	if x != nil {
		return x.Allowed
	}
	return CheckForUpdateResponse_ALLOWED_UNSPECIFIED
}

func (x *CheckForUpdateResponse) GetConsistencyToken() *ConsistencyToken {
	if x != nil {
		return x.ConsistencyToken
	}
	return nil
}

type CheckBulkRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ObjectReference       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBulkRequestItem) Reset() {
	*x = CheckBulkRequestItem{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBulkRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBulkRequestItem) ProtoMessage() {}

func (x *CheckBulkRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBulkRequestItem.ProtoReflect.Descriptor instead.
func (*CheckBulkRequestItem) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{4}
}

func (x *CheckBulkRequestItem) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckBulkRequestItem) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckBulkRequestItem) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type CheckBulkResponseItem struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Allowed       CheckBulkResponseItem_Allowed `protobuf:"varint,1,opt,name=allowed,proto3,enum=kessel.relations.v1beta1.CheckBulkResponseItem_Allowed" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBulkResponseItem) Reset() {
	*x = CheckBulkResponseItem{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBulkResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBulkResponseItem) ProtoMessage() {}

func (x *CheckBulkResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBulkResponseItem.ProtoReflect.Descriptor instead.
func (*CheckBulkResponseItem) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{5}
}

func (x *CheckBulkResponseItem) GetAllowed() CheckBulkResponseItem_Allowed {
	if x != nil {
		return x.Allowed
	}
	return CheckBulkResponseItem_ALLOWED_UNSPECIFIED
}

type CheckBulkResponsePair struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Request *CheckBulkRequestItem  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*CheckBulkResponsePair_Item
	//	*CheckBulkResponsePair_Error
	Response      isCheckBulkResponsePair_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBulkResponsePair) Reset() {
	*x = CheckBulkResponsePair{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBulkResponsePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBulkResponsePair) ProtoMessage() {}

func (x *CheckBulkResponsePair) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBulkResponsePair.ProtoReflect.Descriptor instead.
func (*CheckBulkResponsePair) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{6}
}

func (x *CheckBulkResponsePair) GetRequest() *CheckBulkRequestItem {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CheckBulkResponsePair) GetResponse() isCheckBulkResponsePair_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CheckBulkResponsePair) GetItem() *CheckBulkResponseItem {
	if x != nil {
		if x, ok := x.Response.(*CheckBulkResponsePair_Item); ok {
			return x.Item
		}
	}
	return nil
}

func (x *CheckBulkResponsePair) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Response.(*CheckBulkResponsePair_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCheckBulkResponsePair_Response interface {
	isCheckBulkResponsePair_Response()
}

type CheckBulkResponsePair_Item struct {
	Item *CheckBulkResponseItem `protobuf:"bytes,2,opt,name=item,proto3,oneof"`
}

type CheckBulkResponsePair_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*CheckBulkResponsePair_Item) isCheckBulkResponsePair_Response() {}

func (*CheckBulkResponsePair_Error) isCheckBulkResponsePair_Response() {}

type CheckBulkRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*CheckBulkRequestItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Consistency   *Consistency            `protobuf:"bytes,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBulkRequest) Reset() {
	*x = CheckBulkRequest{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBulkRequest) ProtoMessage() {}

func (x *CheckBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBulkRequest.ProtoReflect.Descriptor instead.
func (*CheckBulkRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{7}
}

func (x *CheckBulkRequest) GetItems() []*CheckBulkRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckBulkRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

type CheckBulkResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Pairs            []*CheckBulkResponsePair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	ConsistencyToken *ConsistencyToken        `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckBulkResponse) Reset() {
	*x = CheckBulkResponse{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBulkResponse) ProtoMessage() {}

func (x *CheckBulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBulkResponse.ProtoReflect.Descriptor instead.
func (*CheckBulkResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{8}
}

func (x *CheckBulkResponse) GetPairs() []*CheckBulkResponsePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *CheckBulkResponse) GetConsistencyToken() *ConsistencyToken {
	if x != nil {
		return x.ConsistencyToken
	}
	return nil
}

var File_kessel_relations_v1beta1_check_proto protoreflect.FileDescriptor

const file_kessel_relations_v1beta1_check_proto_rawDesc = "" +
	"\n" +
	"$kessel/relations/v1beta1/check.proto\x12\x18kessel.relations.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a%kessel/relations/v1beta1/common.proto\x1a\x1bbuf/validate/validate.proto\x1a\x17google/rpc/status.proto\"\x99\x02\n" +
	"\fCheckRequest\x12M\n" +
	"\bresource\x18\x01 \x01(\v2).kessel.relations.v1beta1.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brelation\x12L\n" +
	"\asubject\x18\x03 \x01(\v2*.kessel.relations.v1beta1.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\asubject\x12G\n" +
	"\vconsistency\x18\x04 \x01(\v2%.kessel.relations.v1beta1.ConsistencyR\vconsistency\"\xfc\x01\n" +
	"\rCheckResponse\x12I\n" +
	"\aallowed\x18\x01 \x01(\x0e2/.kessel.relations.v1beta1.CheckResponse.AllowedR\aallowed\x12W\n" +
	"\x11consistency_token\x18\x02 \x01(\v2*.kessel.relations.v1beta1.ConsistencyTokenR\x10consistencyToken\"G\n" +
	"\aAllowed\x12\x17\n" +
	"\x13ALLOWED_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fALLOWED_TRUE\x10\x01\x12\x11\n" +
	"\rALLOWED_FALSE\x10\x02\"\xd9\x01\n" +
	"\x15CheckForUpdateRequest\x12M\n" +
	"\bresource\x18\x01 \x01(\v2).kessel.relations.v1beta1.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brelation\x12L\n" +
	"\asubject\x18\x03 \x01(\v2*.kessel.relations.v1beta1.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\asubject\"\x8e\x02\n" +
	"\x16CheckForUpdateResponse\x12R\n" +
	"\aallowed\x18\x01 \x01(\x0e28.kessel.relations.v1beta1.CheckForUpdateResponse.AllowedR\aallowed\x12W\n" +
	"\x11consistency_token\x18\x02 \x01(\v2*.kessel.relations.v1beta1.ConsistencyTokenR\x10consistencyToken\"G\n" +
	"\aAllowed\x12\x17\n" +
	"\x13ALLOWED_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fALLOWED_TRUE\x10\x01\x12\x11\n" +
	"\rALLOWED_FALSE\x10\x02\"\xd8\x01\n" +
	"\x14CheckBulkRequestItem\x12M\n" +
	"\bresource\x18\x01 \x01(\v2).kessel.relations.v1beta1.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brelation\x12L\n" +
	"\asubject\x18\x03 \x01(\v2*.kessel.relations.v1beta1.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\asubject\"\xb3\x01\n" +
	"\x15CheckBulkResponseItem\x12Q\n" +
	"\aallowed\x18\x01 \x01(\x0e27.kessel.relations.v1beta1.CheckBulkResponseItem.AllowedR\aallowed\"G\n" +
	"\aAllowed\x12\x17\n" +
	"\x13ALLOWED_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fALLOWED_TRUE\x10\x01\x12\x11\n" +
	"\rALLOWED_FALSE\x10\x02\"\xe0\x01\n" +
	"\x15CheckBulkResponsePair\x12H\n" +
	"\arequest\x18\x01 \x01(\v2..kessel.relations.v1beta1.CheckBulkRequestItemR\arequest\x12E\n" +
	"\x04item\x18\x02 \x01(\v2/.kessel.relations.v1beta1.CheckBulkResponseItemH\x00R\x04item\x12*\n" +
	"\x05error\x18\x03 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xab\x01\n" +
	"\x10CheckBulkRequest\x12N\n" +
	"\x05items\x18\x01 \x03(\v2..kessel.relations.v1beta1.CheckBulkRequestItemB\b\xbaH\x05\x92\x01\x02\b\x01R\x05items\x12G\n" +
	"\vconsistency\x18\x02 \x01(\v2%.kessel.relations.v1beta1.ConsistencyR\vconsistency\"\xbd\x01\n" +
	"\x11CheckBulkResponse\x12O\n" +
	"\x05pairs\x18\x01 \x03(\v2/.kessel.relations.v1beta1.CheckBulkResponsePairB\b\xbaH\x05\x92\x01\x02\b\x01R\x05pairs\x12W\n" +
	"\x11consistency_token\x18\x02 \x01(\v2*.kessel.relations.v1beta1.ConsistencyTokenR\x10consistencyToken2\xa9\x03\n" +
	"\x12KesselCheckService\x12s\n" +
	"\x05Check\x12&.kessel.relations.v1beta1.CheckRequest\x1a'.kessel.relations.v1beta1.CheckResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1beta1/check\x12\x97\x01\n" +
	"\x0eCheckForUpdate\x12/.kessel.relations.v1beta1.CheckForUpdateRequest\x1a0.kessel.relations.v1beta1.CheckForUpdateResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1beta1/checkforupdate\x12\x83\x01\n" +
	"\tCheckBulk\x12*.kessel.relations.v1beta1.CheckBulkRequest\x1a+.kessel.relations.v1beta1.CheckBulkResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1beta1/checkbulkBr\n" +
	"(org.project_kessel.api.relations.v1beta1P\x01ZDgithub.com/project-kessel/relations-api/api/kessel/relations/v1beta1b\x06proto3"

var (
	file_kessel_relations_v1beta1_check_proto_rawDescOnce sync.Once
	file_kessel_relations_v1beta1_check_proto_rawDescData []byte
)

func file_kessel_relations_v1beta1_check_proto_rawDescGZIP() []byte {
	file_kessel_relations_v1beta1_check_proto_rawDescOnce.Do(func() {
		file_kessel_relations_v1beta1_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_relations_v1beta1_check_proto_rawDesc), len(file_kessel_relations_v1beta1_check_proto_rawDesc)))
	})
	return file_kessel_relations_v1beta1_check_proto_rawDescData
}

var file_kessel_relations_v1beta1_check_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_kessel_relations_v1beta1_check_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kessel_relations_v1beta1_check_proto_goTypes = []any{
	(CheckResponse_Allowed)(0),          // 0: kessel.relations.v1beta1.CheckResponse.Allowed
	(CheckForUpdateResponse_Allowed)(0), // 1: kessel.relations.v1beta1.CheckForUpdateResponse.Allowed
	(CheckBulkResponseItem_Allowed)(0),  // 2: kessel.relations.v1beta1.CheckBulkResponseItem.Allowed
	(*CheckRequest)(nil),                // 3: kessel.relations.v1beta1.CheckRequest
	(*CheckResponse)(nil),               // 4: kessel.relations.v1beta1.CheckResponse
	(*CheckForUpdateRequest)(nil),       // 5: kessel.relations.v1beta1.CheckForUpdateRequest
	(*CheckForUpdateResponse)(nil),      // 6: kessel.relations.v1beta1.CheckForUpdateResponse
	(*CheckBulkRequestItem)(nil),        // 7: kessel.relations.v1beta1.CheckBulkRequestItem
	(*CheckBulkResponseItem)(nil),       // 8: kessel.relations.v1beta1.CheckBulkResponseItem
	(*CheckBulkResponsePair)(nil),       // 9: kessel.relations.v1beta1.CheckBulkResponsePair
	(*CheckBulkRequest)(nil),            // 10: kessel.relations.v1beta1.CheckBulkRequest
	(*CheckBulkResponse)(nil),           // 11: kessel.relations.v1beta1.CheckBulkResponse
	(*ObjectReference)(nil),             // 12: kessel.relations.v1beta1.ObjectReference
	(*SubjectReference)(nil),            // 13: kessel.relations.v1beta1.SubjectReference
	(*Consistency)(nil),                 // 14: kessel.relations.v1beta1.Consistency
	(*ConsistencyToken)(nil),            // 15: kessel.relations.v1beta1.ConsistencyToken
	(*status.Status)(nil),               // 16: google.rpc.Status
}
var file_kessel_relations_v1beta1_check_proto_depIdxs = []int32{
	12, // 0: kessel.relations.v1beta1.CheckRequest.resource:type_name -> kessel.relations.v1beta1.ObjectReference
	13, // 1: kessel.relations.v1beta1.CheckRequest.subject:type_name -> kessel.relations.v1beta1.SubjectReference
	14, // 2: kessel.relations.v1beta1.CheckRequest.consistency:type_name -> kessel.relations.v1beta1.Consistency
	0,  // 3: kessel.relations.v1beta1.CheckResponse.allowed:type_name -> kessel.relations.v1beta1.CheckResponse.Allowed
	15, // 4: kessel.relations.v1beta1.CheckResponse.consistency_token:type_name -> kessel.relations.v1beta1.ConsistencyToken
	12, // 5: kessel.relations.v1beta1.CheckForUpdateRequest.resource:type_name -> kessel.relations.v1beta1.ObjectReference
	13, // 6: kessel.relations.v1beta1.CheckForUpdateRequest.subject:type_name -> kessel.relations.v1beta1.SubjectReference
	1,  // 7: kessel.relations.v1beta1.CheckForUpdateResponse.allowed:type_name -> kessel.relations.v1beta1.CheckForUpdateResponse.Allowed
	15, // 8: kessel.relations.v1beta1.CheckForUpdateResponse.consistency_token:type_name -> kessel.relations.v1beta1.ConsistencyToken
	12, // 9: kessel.relations.v1beta1.CheckBulkRequestItem.resource:type_name -> kessel.relations.v1beta1.ObjectReference
	13, // 10: kessel.relations.v1beta1.CheckBulkRequestItem.subject:type_name -> kessel.relations.v1beta1.SubjectReference
	2,  // 11: kessel.relations.v1beta1.CheckBulkResponseItem.allowed:type_name -> kessel.relations.v1beta1.CheckBulkResponseItem.Allowed
	7,  // 12: kessel.relations.v1beta1.CheckBulkResponsePair.request:type_name -> kessel.relations.v1beta1.CheckBulkRequestItem
	8,  // 13: kessel.relations.v1beta1.CheckBulkResponsePair.item:type_name -> kessel.relations.v1beta1.CheckBulkResponseItem
	16, // 14: kessel.relations.v1beta1.CheckBulkResponsePair.error:type_name -> google.rpc.Status
	7,  // 15: kessel.relations.v1beta1.CheckBulkRequest.items:type_name -> kessel.relations.v1beta1.CheckBulkRequestItem
	14, // 16: kessel.relations.v1beta1.CheckBulkRequest.consistency:type_name -> kessel.relations.v1beta1.Consistency
	9,  // 17: kessel.relations.v1beta1.CheckBulkResponse.pairs:type_name -> kessel.relations.v1beta1.CheckBulkResponsePair
	15, // 18: kessel.relations.v1beta1.CheckBulkResponse.consistency_token:type_name -> kessel.relations.v1beta1.ConsistencyToken
	3,  // 19: kessel.relations.v1beta1.KesselCheckService.Check:input_type -> kessel.relations.v1beta1.CheckRequest
	5,  // 20: kessel.relations.v1beta1.KesselCheckService.CheckForUpdate:input_type -> kessel.relations.v1beta1.CheckForUpdateRequest
	10, // 21: kessel.relations.v1beta1.KesselCheckService.CheckBulk:input_type -> kessel.relations.v1beta1.CheckBulkRequest
	4,  // 22: kessel.relations.v1beta1.KesselCheckService.Check:output_type -> kessel.relations.v1beta1.CheckResponse
	6,  // 23: kessel.relations.v1beta1.KesselCheckService.CheckForUpdate:output_type -> kessel.relations.v1beta1.CheckForUpdateResponse
	11, // 24: kessel.relations.v1beta1.KesselCheckService.CheckBulk:output_type -> kessel.relations.v1beta1.CheckBulkResponse
	22, // [22:25] is the sub-list for method output_type
	19, // [19:22] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_kessel_relations_v1beta1_check_proto_init() }
func file_kessel_relations_v1beta1_check_proto_init() {
	if File_kessel_relations_v1beta1_check_proto != nil {
		return
	}
	file_kessel_relations_v1beta1_common_proto_init()
	file_kessel_relations_v1beta1_check_proto_msgTypes[6].OneofWrappers = []any{
		(*CheckBulkResponsePair_Item)(nil),
		(*CheckBulkResponsePair_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_relations_v1beta1_check_proto_rawDesc), len(file_kessel_relations_v1beta1_check_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kessel_relations_v1beta1_check_proto_goTypes,
		DependencyIndexes: file_kessel_relations_v1beta1_check_proto_depIdxs,
		EnumInfos:         file_kessel_relations_v1beta1_check_proto_enumTypes,
		MessageInfos:      file_kessel_relations_v1beta1_check_proto_msgTypes,
	}.Build()
	File_kessel_relations_v1beta1_check_proto = out.File
	file_kessel_relations_v1beta1_check_proto_goTypes = nil
	file_kessel_relations_v1beta1_check_proto_depIdxs = nil
}
