// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kessel/relations/v1beta1/check.proto

package v1beta1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckResponse_Allowed int32

const (
	CheckResponse_ALLOWED_UNSPECIFIED CheckResponse_Allowed = 0
	CheckResponse_ALLOWED_TRUE        CheckResponse_Allowed = 1
	CheckResponse_ALLOWED_FALSE       CheckResponse_Allowed = 2 // e.g.  ALLOWED_CONDITIONAL = 3;
)

// Enum value maps for CheckResponse_Allowed.
var (
	CheckResponse_Allowed_name = map[int32]string{
		0: "ALLOWED_UNSPECIFIED",
		1: "ALLOWED_TRUE",
		2: "ALLOWED_FALSE",
	}
	CheckResponse_Allowed_value = map[string]int32{
		"ALLOWED_UNSPECIFIED": 0,
		"ALLOWED_TRUE":        1,
		"ALLOWED_FALSE":       2,
	}
)

func (x CheckResponse_Allowed) Enum() *CheckResponse_Allowed {
	p := new(CheckResponse_Allowed)
	*p = x
	return p
}

func (x CheckResponse_Allowed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckResponse_Allowed) Descriptor() protoreflect.EnumDescriptor {
	return file_kessel_relations_v1beta1_check_proto_enumTypes[0].Descriptor()
}

func (CheckResponse_Allowed) Type() protoreflect.EnumType {
	return &file_kessel_relations_v1beta1_check_proto_enumTypes[0]
}

func (x CheckResponse_Allowed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckResponse_Allowed.Descriptor instead.
func (CheckResponse_Allowed) EnumDescriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{1, 0}
}

type CheckForUpdateResponse_Allowed int32

const (
	CheckForUpdateResponse_ALLOWED_UNSPECIFIED CheckForUpdateResponse_Allowed = 0
	CheckForUpdateResponse_ALLOWED_TRUE        CheckForUpdateResponse_Allowed = 1
	CheckForUpdateResponse_ALLOWED_FALSE       CheckForUpdateResponse_Allowed = 2 // e.g.  ALLOWED_CONDITIONAL = 3;
)

// Enum value maps for CheckForUpdateResponse_Allowed.
var (
	CheckForUpdateResponse_Allowed_name = map[int32]string{
		0: "ALLOWED_UNSPECIFIED",
		1: "ALLOWED_TRUE",
		2: "ALLOWED_FALSE",
	}
	CheckForUpdateResponse_Allowed_value = map[string]int32{
		"ALLOWED_UNSPECIFIED": 0,
		"ALLOWED_TRUE":        1,
		"ALLOWED_FALSE":       2,
	}
)

func (x CheckForUpdateResponse_Allowed) Enum() *CheckForUpdateResponse_Allowed {
	p := new(CheckForUpdateResponse_Allowed)
	*p = x
	return p
}

func (x CheckForUpdateResponse_Allowed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckForUpdateResponse_Allowed) Descriptor() protoreflect.EnumDescriptor {
	return file_kessel_relations_v1beta1_check_proto_enumTypes[1].Descriptor()
}

func (CheckForUpdateResponse_Allowed) Type() protoreflect.EnumType {
	return &file_kessel_relations_v1beta1_check_proto_enumTypes[1]
}

func (x CheckForUpdateResponse_Allowed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckForUpdateResponse_Allowed.Descriptor instead.
func (CheckForUpdateResponse_Allowed) EnumDescriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{3, 0}
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ObjectReference       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Consistency   *Consistency           `protobuf:"bytes,4,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CheckRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

type CheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          CheckResponse_Allowed  `protobuf:"varint,1,opt,name=allowed,proto3,enum=kessel.relations.v1beta1.CheckResponse_Allowed" json:"allowed,omitempty"`
	ConsistencyToken *ConsistencyToken      `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() CheckResponse_Allowed {
	if x != nil {
		return x.Allowed
	}
	return CheckResponse_ALLOWED_UNSPECIFIED
}

func (x *CheckResponse) GetConsistencyToken() *ConsistencyToken {
	if x != nil {
		return x.ConsistencyToken
	}
	return nil
}

type CheckForUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ObjectReference       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdateRequest) Reset() {
	*x = CheckForUpdateRequest{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdateRequest) ProtoMessage() {}

func (x *CheckForUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckForUpdateRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{2}
}

func (x *CheckForUpdateRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckForUpdateRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckForUpdateRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type CheckForUpdateResponse struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Allowed          CheckForUpdateResponse_Allowed `protobuf:"varint,1,opt,name=allowed,proto3,enum=kessel.relations.v1beta1.CheckForUpdateResponse_Allowed" json:"allowed,omitempty"`
	ConsistencyToken *ConsistencyToken              `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckForUpdateResponse) Reset() {
	*x = CheckForUpdateResponse{}
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdateResponse) ProtoMessage() {}

func (x *CheckForUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_check_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckForUpdateResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_check_proto_rawDescGZIP(), []int{3}
}

func (x *CheckForUpdateResponse) GetAllowed() CheckForUpdateResponse_Allowed {
	if x != nil {
		return x.Allowed
	}
	return CheckForUpdateResponse_ALLOWED_UNSPECIFIED
}

func (x *CheckForUpdateResponse) GetConsistencyToken() *ConsistencyToken {
	if x != nil {
		return x.ConsistencyToken
	}
	return nil
}

var File_kessel_relations_v1beta1_check_proto protoreflect.FileDescriptor

const file_kessel_relations_v1beta1_check_proto_rawDesc = "" +
	"\n" +
	"$kessel/relations/v1beta1/check.proto\x12\x18kessel.relations.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a%kessel/relations/v1beta1/common.proto\x1a\x1bbuf/validate/validate.proto\"\x99\x02\n" +
	"\fCheckRequest\x12M\n" +
	"\bresource\x18\x01 \x01(\v2).kessel.relations.v1beta1.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brelation\x12L\n" +
	"\asubject\x18\x03 \x01(\v2*.kessel.relations.v1beta1.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\asubject\x12G\n" +
	"\vconsistency\x18\x04 \x01(\v2%.kessel.relations.v1beta1.ConsistencyR\vconsistency\"\xfc\x01\n" +
	"\rCheckResponse\x12I\n" +
	"\aallowed\x18\x01 \x01(\x0e2/.kessel.relations.v1beta1.CheckResponse.AllowedR\aallowed\x12W\n" +
	"\x11consistency_token\x18\x02 \x01(\v2*.kessel.relations.v1beta1.ConsistencyTokenR\x10consistencyToken\"G\n" +
	"\aAllowed\x12\x17\n" +
	"\x13ALLOWED_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fALLOWED_TRUE\x10\x01\x12\x11\n" +
	"\rALLOWED_FALSE\x10\x02\"\xd9\x01\n" +
	"\x15CheckForUpdateRequest\x12M\n" +
	"\bresource\x18\x01 \x01(\v2).kessel.relations.v1beta1.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brelation\x12L\n" +
	"\asubject\x18\x03 \x01(\v2*.kessel.relations.v1beta1.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\asubject\"\x8e\x02\n" +
	"\x16CheckForUpdateResponse\x12R\n" +
	"\aallowed\x18\x01 \x01(\x0e28.kessel.relations.v1beta1.CheckForUpdateResponse.AllowedR\aallowed\x12W\n" +
	"\x11consistency_token\x18\x02 \x01(\v2*.kessel.relations.v1beta1.ConsistencyTokenR\x10consistencyToken\"G\n" +
	"\aAllowed\x12\x17\n" +
	"\x13ALLOWED_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fALLOWED_TRUE\x10\x01\x12\x11\n" +
	"\rALLOWED_FALSE\x10\x022\xa3\x02\n" +
	"\x12KesselCheckService\x12s\n" +
	"\x05Check\x12&.kessel.relations.v1beta1.CheckRequest\x1a'.kessel.relations.v1beta1.CheckResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1beta1/check\x12\x97\x01\n" +
	"\x0eCheckForUpdate\x12/.kessel.relations.v1beta1.CheckForUpdateRequest\x1a0.kessel.relations.v1beta1.CheckForUpdateResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1beta1/checkforupdateBr\n" +
	"(org.project_kessel.api.relations.v1beta1P\x01ZDgithub.com/project-kessel/relations-api/api/kessel/relations/v1beta1b\x06proto3"

var (
	file_kessel_relations_v1beta1_check_proto_rawDescOnce sync.Once
	file_kessel_relations_v1beta1_check_proto_rawDescData []byte
)

func file_kessel_relations_v1beta1_check_proto_rawDescGZIP() []byte {
	file_kessel_relations_v1beta1_check_proto_rawDescOnce.Do(func() {
		file_kessel_relations_v1beta1_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_relations_v1beta1_check_proto_rawDesc), len(file_kessel_relations_v1beta1_check_proto_rawDesc)))
	})
	return file_kessel_relations_v1beta1_check_proto_rawDescData
}

var file_kessel_relations_v1beta1_check_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kessel_relations_v1beta1_check_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kessel_relations_v1beta1_check_proto_goTypes = []any{
	(CheckResponse_Allowed)(0),          // 0: kessel.relations.v1beta1.CheckResponse.Allowed
	(CheckForUpdateResponse_Allowed)(0), // 1: kessel.relations.v1beta1.CheckForUpdateResponse.Allowed
	(*CheckRequest)(nil),                // 2: kessel.relations.v1beta1.CheckRequest
	(*CheckResponse)(nil),               // 3: kessel.relations.v1beta1.CheckResponse
	(*CheckForUpdateRequest)(nil),       // 4: kessel.relations.v1beta1.CheckForUpdateRequest
	(*CheckForUpdateResponse)(nil),      // 5: kessel.relations.v1beta1.CheckForUpdateResponse
	(*ObjectReference)(nil),             // 6: kessel.relations.v1beta1.ObjectReference
	(*SubjectReference)(nil),            // 7: kessel.relations.v1beta1.SubjectReference
	(*Consistency)(nil),                 // 8: kessel.relations.v1beta1.Consistency
	(*ConsistencyToken)(nil),            // 9: kessel.relations.v1beta1.ConsistencyToken
}
var file_kessel_relations_v1beta1_check_proto_depIdxs = []int32{
	6,  // 0: kessel.relations.v1beta1.CheckRequest.resource:type_name -> kessel.relations.v1beta1.ObjectReference
	7,  // 1: kessel.relations.v1beta1.CheckRequest.subject:type_name -> kessel.relations.v1beta1.SubjectReference
	8,  // 2: kessel.relations.v1beta1.CheckRequest.consistency:type_name -> kessel.relations.v1beta1.Consistency
	0,  // 3: kessel.relations.v1beta1.CheckResponse.allowed:type_name -> kessel.relations.v1beta1.CheckResponse.Allowed
	9,  // 4: kessel.relations.v1beta1.CheckResponse.consistency_token:type_name -> kessel.relations.v1beta1.ConsistencyToken
	6,  // 5: kessel.relations.v1beta1.CheckForUpdateRequest.resource:type_name -> kessel.relations.v1beta1.ObjectReference
	7,  // 6: kessel.relations.v1beta1.CheckForUpdateRequest.subject:type_name -> kessel.relations.v1beta1.SubjectReference
	1,  // 7: kessel.relations.v1beta1.CheckForUpdateResponse.allowed:type_name -> kessel.relations.v1beta1.CheckForUpdateResponse.Allowed
	9,  // 8: kessel.relations.v1beta1.CheckForUpdateResponse.consistency_token:type_name -> kessel.relations.v1beta1.ConsistencyToken
	2,  // 9: kessel.relations.v1beta1.KesselCheckService.Check:input_type -> kessel.relations.v1beta1.CheckRequest
	4,  // 10: kessel.relations.v1beta1.KesselCheckService.CheckForUpdate:input_type -> kessel.relations.v1beta1.CheckForUpdateRequest
	3,  // 11: kessel.relations.v1beta1.KesselCheckService.Check:output_type -> kessel.relations.v1beta1.CheckResponse
	5,  // 12: kessel.relations.v1beta1.KesselCheckService.CheckForUpdate:output_type -> kessel.relations.v1beta1.CheckForUpdateResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_kessel_relations_v1beta1_check_proto_init() }
func file_kessel_relations_v1beta1_check_proto_init() {
	if File_kessel_relations_v1beta1_check_proto != nil {
		return
	}
	file_kessel_relations_v1beta1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_relations_v1beta1_check_proto_rawDesc), len(file_kessel_relations_v1beta1_check_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kessel_relations_v1beta1_check_proto_goTypes,
		DependencyIndexes: file_kessel_relations_v1beta1_check_proto_depIdxs,
		EnumInfos:         file_kessel_relations_v1beta1_check_proto_enumTypes,
		MessageInfos:      file_kessel_relations_v1beta1_check_proto_msgTypes,
	}.Build()
	File_kessel_relations_v1beta1_check_proto = out.File
	file_kessel_relations_v1beta1_check_proto_goTypes = nil
	file_kessel_relations_v1beta1_check_proto_depIdxs = nil
}
