// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: kessel/relations/v1beta1/fencing.proto

package v1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KesselFencingService_AcquireLock_FullMethodName = "/kessel.relations.v1beta1.KesselFencingService/AcquireLock"
)

// KesselFencingServiceClient is the client API for KesselFencingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KesselFencingServiceClient interface {
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
}

type kesselFencingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKesselFencingServiceClient(cc grpc.ClientConnInterface) KesselFencingServiceClient {
	return &kesselFencingServiceClient{cc}
}

func (c *kesselFencingServiceClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, KesselFencingService_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KesselFencingServiceServer is the server API for KesselFencingService service.
// All implementations must embed UnimplementedKesselFencingServiceServer
// for forward compatibility.
type KesselFencingServiceServer interface {
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	mustEmbedUnimplementedKesselFencingServiceServer()
}

// UnimplementedKesselFencingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKesselFencingServiceServer struct{}

func (UnimplementedKesselFencingServiceServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedKesselFencingServiceServer) mustEmbedUnimplementedKesselFencingServiceServer() {}
func (UnimplementedKesselFencingServiceServer) testEmbeddedByValue()                              {}

// UnsafeKesselFencingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KesselFencingServiceServer will
// result in compilation errors.
type UnsafeKesselFencingServiceServer interface {
	mustEmbedUnimplementedKesselFencingServiceServer()
}

func RegisterKesselFencingServiceServer(s grpc.ServiceRegistrar, srv KesselFencingServiceServer) {
	// If the following call pancis, it indicates UnimplementedKesselFencingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KesselFencingService_ServiceDesc, srv)
}

func _KesselFencingService_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KesselFencingServiceServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KesselFencingService_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KesselFencingServiceServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KesselFencingService_ServiceDesc is the grpc.ServiceDesc for KesselFencingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KesselFencingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kessel.relations.v1beta1.KesselFencingService",
	HandlerType: (*KesselFencingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireLock",
			Handler:    _KesselFencingService_AcquireLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kessel/relations/v1beta1/fencing.proto",
}
