// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             (unknown)
// source: kessel/relations/v1beta1/fencing.proto

package v1beta1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationKesselFencingServiceAcquireLock = "/kessel.relations.v1beta1.KesselFencingService/AcquireLock"

type KesselFencingServiceHTTPServer interface {
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
}

func RegisterKesselFencingServiceHTTPServer(s *http.Server, srv KesselFencingServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1beta1/acquirelock", _KesselFencingService_AcquireLock0_HTTP_Handler(srv))
}

func _KesselFencingService_AcquireLock0_HTTP_Handler(srv KesselFencingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AcquireLockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKesselFencingServiceAcquireLock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AcquireLock(ctx, req.(*AcquireLockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AcquireLockResponse)
		return ctx.Result(200, reply)
	}
}

type KesselFencingServiceHTTPClient interface {
	AcquireLock(ctx context.Context, req *AcquireLockRequest, opts ...http.CallOption) (rsp *AcquireLockResponse, err error)
}

type KesselFencingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewKesselFencingServiceHTTPClient(client *http.Client) KesselFencingServiceHTTPClient {
	return &KesselFencingServiceHTTPClientImpl{client}
}

func (c *KesselFencingServiceHTTPClientImpl) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...http.CallOption) (*AcquireLockResponse, error) {
	var out AcquireLockResponse
	pattern := "/v1beta1/acquirelock"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKesselFencingServiceAcquireLock))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
