// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kessel/relations/v1beta1/fencing.proto

package v1beta1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcquireLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	ExistingToken *string                `protobuf:"bytes,2,opt,name=existing_token,json=existingToken,proto3,oneof" json:"existing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockRequest) Reset() {
	*x = AcquireLockRequest{}
	mi := &file_kessel_relations_v1beta1_fencing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockRequest) ProtoMessage() {}

func (x *AcquireLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_fencing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockRequest.ProtoReflect.Descriptor instead.
func (*AcquireLockRequest) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_fencing_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireLockRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *AcquireLockRequest) GetExistingToken() string {
	if x != nil && x.ExistingToken != nil {
		return *x.ExistingToken
	}
	return ""
}

type AcquireLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewToken      string                 `protobuf:"bytes,1,opt,name=new_token,json=newToken,proto3" json:"new_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockResponse) Reset() {
	*x = AcquireLockResponse{}
	mi := &file_kessel_relations_v1beta1_fencing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockResponse) ProtoMessage() {}

func (x *AcquireLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_fencing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockResponse.ProtoReflect.Descriptor instead.
func (*AcquireLockResponse) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_fencing_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireLockResponse) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

type FencingCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FencingCheck) Reset() {
	*x = FencingCheck{}
	mi := &file_kessel_relations_v1beta1_fencing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FencingCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FencingCheck) ProtoMessage() {}

func (x *FencingCheck) ProtoReflect() protoreflect.Message {
	mi := &file_kessel_relations_v1beta1_fencing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FencingCheck.ProtoReflect.Descriptor instead.
func (*FencingCheck) Descriptor() ([]byte, []int) {
	return file_kessel_relations_v1beta1_fencing_proto_rawDescGZIP(), []int{2}
}

func (x *FencingCheck) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *FencingCheck) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_kessel_relations_v1beta1_fencing_proto protoreflect.FileDescriptor

const file_kessel_relations_v1beta1_fencing_proto_rawDesc = "" +
	"\n" +
	"&kessel/relations/v1beta1/fencing.proto\x12\x18kessel.relations.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\"{\n" +
	"\x12AcquireLockRequest\x12&\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"identifier\x12*\n" +
	"\x0eexisting_token\x18\x02 \x01(\tH\x00R\rexistingToken\x88\x01\x01B\x11\n" +
	"\x0f_existing_token\"2\n" +
	"\x13AcquireLockResponse\x12\x1b\n" +
	"\tnew_token\x18\x01 \x01(\tR\bnewToken\"T\n" +
	"\fFencingCheck\x12&\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"identifier\x12\x1c\n" +
	"\x05token\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05token2\xa4\x01\n" +
	"\x14KesselFencingService\x12\x8b\x01\n" +
	"\vAcquireLock\x12,.kessel.relations.v1beta1.AcquireLockRequest\x1a-.kessel.relations.v1beta1.AcquireLockResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1beta1/acquirelockBr\n" +
	"(org.project_kessel.api.relations.v1beta1P\x01ZDgithub.com/project-kessel/relations-api/api/kessel/relations/v1beta1b\x06proto3"

var (
	file_kessel_relations_v1beta1_fencing_proto_rawDescOnce sync.Once
	file_kessel_relations_v1beta1_fencing_proto_rawDescData []byte
)

func file_kessel_relations_v1beta1_fencing_proto_rawDescGZIP() []byte {
	file_kessel_relations_v1beta1_fencing_proto_rawDescOnce.Do(func() {
		file_kessel_relations_v1beta1_fencing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kessel_relations_v1beta1_fencing_proto_rawDesc), len(file_kessel_relations_v1beta1_fencing_proto_rawDesc)))
	})
	return file_kessel_relations_v1beta1_fencing_proto_rawDescData
}

var file_kessel_relations_v1beta1_fencing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kessel_relations_v1beta1_fencing_proto_goTypes = []any{
	(*AcquireLockRequest)(nil),  // 0: kessel.relations.v1beta1.AcquireLockRequest
	(*AcquireLockResponse)(nil), // 1: kessel.relations.v1beta1.AcquireLockResponse
	(*FencingCheck)(nil),        // 2: kessel.relations.v1beta1.FencingCheck
}
var file_kessel_relations_v1beta1_fencing_proto_depIdxs = []int32{
	0, // 0: kessel.relations.v1beta1.KesselFencingService.AcquireLock:input_type -> kessel.relations.v1beta1.AcquireLockRequest
	1, // 1: kessel.relations.v1beta1.KesselFencingService.AcquireLock:output_type -> kessel.relations.v1beta1.AcquireLockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kessel_relations_v1beta1_fencing_proto_init() }
func file_kessel_relations_v1beta1_fencing_proto_init() {
	if File_kessel_relations_v1beta1_fencing_proto != nil {
		return
	}
	file_kessel_relations_v1beta1_fencing_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kessel_relations_v1beta1_fencing_proto_rawDesc), len(file_kessel_relations_v1beta1_fencing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kessel_relations_v1beta1_fencing_proto_goTypes,
		DependencyIndexes: file_kessel_relations_v1beta1_fencing_proto_depIdxs,
		MessageInfos:      file_kessel_relations_v1beta1_fencing_proto_msgTypes,
	}.Build()
	File_kessel_relations_v1beta1_fencing_proto = out.File
	file_kessel_relations_v1beta1_fencing_proto_goTypes = nil
	file_kessel_relations_v1beta1_fencing_proto_depIdxs = nil
}
