apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: relationships
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: postgres
      name: postgres
      namespace: ${NAMESPACE}
    spec:
      selector:
        matchLabels:
          app: postgres
      template:
        metadata:
          labels:
            app: postgres
        spec:
          containers:
          - env:
            - name: POSTGRESQL_DATABASE
              value: ${POSTGRES_DB}
            - name: POSTGRESQL_USER
              value: ${POSTGRES_USER}
            - name: POSTGRESQL_PASSWORD
              value: ${POSTGRES_PASSWORD}
            - name: PGDATA
              value: /temp/data
            image: registry.redhat.io/rhel9/postgresql-16:9.5-1744136555
            imagePullPolicy: Always
            name: postgres
            ports:
            - containerPort: 5432
              protocol: TCP
            resources:
              limits:
                cpu: 60m
                memory: 256Mi
              requests:
                cpu: 30m
                memory: 128Mi
          restartPolicy: Always

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: postgres
      name: postgres
      namespace: ${NAMESPACE}
    spec:
      ports:
      - name: http
        port: 5432
        protocol: TCP
      selector:
        app: postgres
  - apiVersion: v1
    kind: Secret
    metadata:
      name: dev-spicedb-config
    stringData:
      preshared_key: "averysecretpresharedkey"
      datastore_uri: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.${NAMESPACE}.svc.cluster.local:5432/${POSTGRES_DB}?sslmode=disable
parameters:
  - description: Namespace to deploy into
    name: NAMESPACE
    value: ${NAMESPACE} 
  - description: Postgres DB name
    name: POSTGRES_DB
    value: ${POSTGRES_DB}
  - description: Postgres DB username
    name: POSTGRES_USER
    value: ${POSTGRES_USER}   
  - description: Postgres DB password
    name: POSTGRES_PASSWORD
    value: ${POSTGRES_PASSWORD}           
