---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb-cr
  namespace: spicedb
spec:
  config:
    logLevel: debug
    datastoreEngine: postgres
    #datastoreTLSSecretName: datastore-tls
    replicas: 2
    image: ghcr.io/authzed/spicedb:v1.31.0
  secretName: spicedb-config
---
apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config
  namespace: spicedb
stringData:
  datastore_uri: "postgres://postgres:yPsw5e6ab4bvAGe5H@postgres:5432/spicedb?sslmode=disable"
  preshared_key: "foobar"
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: datastore-tls
#   namespace: spicedb
# stringData:
#   ca.crt: |
#     -----BEGIN CERTIFICATE-----
#    --- example aws rds ca cert
#     -----END CERTIFICATE-----
# ---