{
 "title": "Kessel - Relations API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values({job=\"kessel-relations-api\"},operation)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Detailed Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(server_requests_seconds_bucket_count{job=\"kessel-relations-api\"}[10m]))",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "Success",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n    sum(rate(server_requests_code_total{job=\"kessel-relations-api\", code=\"0\"}[10m]))\n+\n    sum(rate(server_requests_code_total{ job=\"kessel-relations-api\", code=\"200\"}[10m]))\n)\n /\nsum(rate(server_requests_seconds_bucket_count{job=\"kessel-relations-api\"}[10m]))"
      }
     ]
    },
    {
     "title": "Latency P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\"}[10m])))",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "Check Permission P50",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselCheckService/Check\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "Check Permission P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselCheckService/Check\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "Check Permission P99",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselCheckService/Check\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupResources P50",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselLookupService/LookupResources\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupResources P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselLookupService/LookupResources\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupResources P99",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselLookupService/LookupResources\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupSubjects P50",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselLookupService/LookupSubjects\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupSubjects P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselLookupService/LookupSubjects\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupSubjects P99",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\",operation=\"/kessel.relations.v1beta1.KesselLookupService/LookupSubjects\"}[10m])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    }
   ]
  },
  { "title": "Relations-Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status Code Totals (By Operation)",
   "type": "table",
   "description": "over selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by (code,operation) (increase(server_requests_code_total{job=\"kessel-relations-api\", operation=~\"$operation\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Status Codes Per Second ",
   "type": "timeseries",
   "description": "over selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by (code)(rate(server_requests_code_total{job=\"kessel-relations-api\", code!~\"200|0\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Requests below 250ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(server_requests_seconds_bucket_bucket{le=\"0.25\", operation=~\"$operation\", job=\"kessel-relations-api\"}[5m])) by (operation)\n/\nsum(rate(server_requests_seconds_bucket_count{job=\"kessel-relations-api\"}[5m])) by (operation)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile",
   "type": "timeseries",
   "description": "rate of requests in seconds at X percentile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(server_requests_seconds_bucket_bucket{operation=~\"$operation\", job=\"kessel-relations-api\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(server_requests_seconds_bucket_bucket{operation=~\"$operation\", job=\"kessel-relations-api\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(server_requests_seconds_bucket_count{operation=~\"$operation\", job=\"kessel-relations-api\"}[$__rate_interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\", operation=~\"$operation\"}[$__rate_interval])))",
     "legendFormat": "99% {{operation}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(server_requests_seconds_bucket_bucket{job=\"kessel-relations-api\", operation=~\"$operation\"}[$__rate_interval])))",
     "legendFormat": "95% {{operation}}"
    }
   ]
  },
  { "title": "Other stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{job=\"kessel-relations-api\"})",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "avg(rate(go_memstats_alloc_bytes_total{job=\"kessel-relations-api\"}[$__interval]))",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{job=\"kessel-relations-api\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{job=\"kessel-relations-api\"})",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) by (mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_goroutines{job=\"kessel-relations-api\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$__interval])\n\n",
     "legendFormat": "bytes allocated"
    }
   ]
  },
  {
   "title": "Network Bandwidth (Bytes transmitted):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[$__interval])\n",
     "legendFormat": "bytes allocated"
    }
   ]
  }
 ]
}