{
 "title": "Kessel  - Relations API data sync",
 "description": "Measuring characteristics of data sync between services and relations-api",
 "tags": [ "kessel" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Rbac -> Relations API: Lag detected",
   "type": "state-timeline",
   "description": "Periods of lag, when the rate of replication events generated exceeds the rate at which it's consumed by relations-api.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kafka_connect_source_task_source_record_write_total{connector=\"rbac-debezium\"}[3m])) -0.009 - sum(rate(kafka_connect_sink_task_sink_record_send_total{connector=\"relations-sink-connector\"}[3m])) > 0",
     "legendFormat": "__auto"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         100
        ],
        "type": "within_range"
       },
       "operator": { "type": "when" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "min"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "mean",
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "RBAC -> Relations API: Rate of Rbac replication event creation minus rate of relations-api consumption ",
   "type": "timeseries",
   "description": "The rate at which replication events are created and propagated should be matched closely by the rate at which replication events are processed and relations are applied to relations-api.",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kafka_connect_source_task_source_record_write_total{connector=\"rbac-debezium\"}[3m])) -0.009 - sum(rate(kafka_connect_sink_task_sink_record_send_total{connector=\"relations-sink-connector\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rbac replication event count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_connect_source_task_source_record_write_total{connector=\"rbac-debezium\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relations API applied replication event count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_connect_sink_task_sink_record_send_total{connector=\"relations-sink-connector\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}