{
 "title": "Kessel - SpiceDB",
 "description": "spicedb service monitoring",
 "tags": [
  "gRPC",
  "go",
  "spicedb"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "interval",
    "label": "Summary interval (set to roughly test duration, but no greater)",
    "query": "1m,5m,10m,15m,25m,30m,1h"
   },
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Detailed Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Success",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n    sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code=\"OK\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$interval])) + \n    (sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code=\"NotFound\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$interval])) or vector(0))\n)\n / \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Latency P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "cache rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(spicedb_cache_hits_total{cache=\"dispatch\",job=\"$job\"}[$interval]))\n/ \n(\n    sum(rate(spicedb_cache_hits_total{cache=\"dispatch\",job=\"$job\"}[$interval]) +\n    rate(spicedb_cache_misses_total{cache=\"dispatch\",job=\"$job\"}[$interval]))\n)"
      }
     ]
    },
    {
     "title": "Check Permission RPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"$job\", grpc_method=\"CheckPermission\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Check Permission P50",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "Check Permission P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "Check Permission P99",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupSubjects RPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"$job\", grpc_method=\"LookupSubjects\"}[$interval]))"
      }
     ]
    },
    {
     "title": "LookupSubjects P50",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"LookupSubjects\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupSubjects P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"LookupSubjects\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupSubjects P99",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"LookupSubjects\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupResources RPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"$job\", grpc_method=\"LookupResources\"}[$interval]))"
      }
     ]
    },
    {
     "title": "LookupResourcesP50",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"LookupResources\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupResources P95",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"LookupResources\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    },
    {
     "title": "LookupResources P99",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"LookupResources\"}[$interval])) by (le)\n)",
       "legendFormat": "95%"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code=\"OK\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval])) + \n    (sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code=\"NotFound\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval])) or vector(0))\n)\n / \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))",
     "legendFormat": "Success rate"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))/ sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval])) * 100",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(grpc_server_started_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(grpc_server_started_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Check Permission P50",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\",grpc_type=\"unary\"}[$__rate_interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Check Permission P95",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\",grpc_type=\"unary\"}[$__rate_interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Check Permission P99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$__rate_interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Check Permission RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\", grpc_method=\"CheckPermission\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "LookupResources RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\", grpc_method=\"LookupResources\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LookupSubjects RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\", grpc_method=\"LookupSubjects\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Spicedb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cache activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(spicedb_cache_cost_added_bytes{job=\"$job\"}[$__rate_interval])) by (cache)",
     "legendFormat": "{{cache}}: Added"
    },
    {
     "expr": "sum(rate(spicedb_cache_cost_evicted_bytes{job=\"$job\"}[$__interval])) by (cache)",
     "legendFormat": "{{cache}}: Evicted"
    }
   ]
  },
  {
   "title": "cache rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (cache) (rate(spicedb_cache_hits_total{job=\"$job\"}[$interval]))\n/ \n(\n    sum by (cache) (rate(spicedb_cache_hits_total{job=\"$job\"}[$interval]) +\n    rate(spicedb_cache_misses_total{job=\"$job\"}[$interval]))\n)",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code=\"OK\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))\n/ sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"InvalidArgument\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"NotFound\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"AlreadyExists\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"Unauthenticated\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"PermissionDenied\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"FailedPrecondition\"}[$__rate_interval]))\n)/ sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))",
     "legendFormat": "ClientError"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"Internal\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"Unknown\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"Unavailable\"}[$__rate_interval])) +\nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\",grpc_code=\"Unimplemented\"}[$__rate_interval]))\n)/ sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))",
     "legendFormat": "ServerError"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\"}[$__rate_interval])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$__rate_interval])) by (grpc_service,le)\n)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval])) by (le, grpc_method)\n)",
     "legendFormat": "99% {{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__interval])) by (le, grpc_method)\n)",
     "legendFormat": "95% {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Status distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\"}[$__rate_interval])) by (grpc_code)\n/ ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Check permission Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\", grpc_method=\"CheckPermission\"}[$__rate_interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$__interval])) by (le)\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$__interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$__interval])) by (le)\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$__interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$__interval])) by (le)\n)",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_method=\"CheckPermission\"}[$__interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Failure RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",job=\"$job\",grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Request distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\"}[$__rate_interval])) by (grpc_service) \n/ ignoring(grpc_service) group_left sum(rate(grpc_server_started_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "RPC type distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\"}[$__rate_interval])) by (grpc_type)\n/ ignoring(grpc_type) group_left sum(rate(grpc_server_handled_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_type}}"
    }
   ]
  },
  {
   "title": "Spicedb datastore Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(spicedb_datastore_query_latency_bucket{job=\"$job\"}[$__rate_interval])) by (le, operation)\n)",
     "legendFormat": "95%: {{operation}}"
    }
   ]
  },
  {
   "title": "Datastore Query Latency [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(spicedb_datastore_query_latency_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(spicedb_datastore_query_latency_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spicedb datastore RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(spicedb_datastore_query_latency_count{job=\"$job\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PG read conn pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum by (pod) (pgxpool_acquired_conns{job=\"$job\",pool_usage=\"read\"})",
     "legendFormat": "acquired: {{pod}}"
    },
    {
     "expr": "sum by (pod) (pgxpool_idle_conns{job=\"$job\",pool_usage=\"read\"})",
     "legendFormat": "idle: {{pod}}"
    },
    {
     "expr": "sum by (pod) (pgxpool_constructing_conns{job=\"$job\",pool_usage=\"read\"})",
     "legendFormat": "constr: {{pod}}"
    }
   ]
  },
  {
   "title": "Status Code Totals  (By Operation)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (grpc_server_handled_total{grpc_method=~\".*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PG write conn pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum by (pod) (pgxpool_acquired_conns{job=\"$job\",pool_usage=\"write\"})",
     "legendFormat": "acquired: {{pod}}"
    },
    {
     "expr": "sum by (pod) (pgxpool_idle_conns{job=\"$job\",pool_usage=\"write\"})",
     "legendFormat": "idle: {{pod}}"
    },
    {
     "expr": "sum by (pod) (pgxpool_constructing_conns{job=\"$job\",pool_usage=\"write\"})",
     "legendFormat": "constr: {{pod}}"
    }
   ]
  },
  {
   "title": "Sum connection acquire time (cluster-wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (pool_usage) (rate(pgxpool_acquire_duration_ns{job=\"$job\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Empty Acquires/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum by (pod, pool_usage) (rate(pgxpool_empty_acquire{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pool_usage}}: {{pod}}"
    }
   ]
  },
  {
   "title": "% Requests below 562ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handling_seconds_bucket{le=\"0.562\", grpc_method=~\".*\"}[5m])) by (grpc_method)\n/\nsum(rate(grpc_server_handling_seconds_count[5m])) by (grpc_method)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile",
   "type": "timeseries",
   "description": "rate of requests in seconds at X percentile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=~\".*\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=~\".*\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  { "title": "go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{job=\"$job\"})",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "avg(rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$__interval]))",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{job=\"$job\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{job=\"$job\"})",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Spicedb Datastore GC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(spicedb_datastore_gc_duration_seconds_sum{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutines{job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) by (mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[$interval])\n\n",
     "legendFormat": "bytes allocated"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Network Bandwidth (Bytes transmitted):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total[$interval])\n",
     "legendFormat": "bytes allocated"
    }
   ]
  }
 ]
}