// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.4
// source: rebac/v1/check.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckResponse_Allowed int32

const (
	CheckResponse_ALLOWED_UNSPECIFIED CheckResponse_Allowed = 0
	CheckResponse_ALLOWED_TRUE        CheckResponse_Allowed = 1
	CheckResponse_ALLOWED_FALSE       CheckResponse_Allowed = 2 // e.g.  ALLOWED_CONDITIONAL = 3;
)

// Enum value maps for CheckResponse_Allowed.
var (
	CheckResponse_Allowed_name = map[int32]string{
		0: "ALLOWED_UNSPECIFIED",
		1: "ALLOWED_TRUE",
		2: "ALLOWED_FALSE",
	}
	CheckResponse_Allowed_value = map[string]int32{
		"ALLOWED_UNSPECIFIED": 0,
		"ALLOWED_TRUE":        1,
		"ALLOWED_FALSE":       2,
	}
)

func (x CheckResponse_Allowed) Enum() *CheckResponse_Allowed {
	p := new(CheckResponse_Allowed)
	*p = x
	return p
}

func (x CheckResponse_Allowed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckResponse_Allowed) Descriptor() protoreflect.EnumDescriptor {
	return file_rebac_v1_check_proto_enumTypes[0].Descriptor()
}

func (CheckResponse_Allowed) Type() protoreflect.EnumType {
	return &file_rebac_v1_check_proto_enumTypes[0]
}

func (x CheckResponse_Allowed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckResponse_Allowed.Descriptor instead.
func (CheckResponse_Allowed) EnumDescriptor() ([]byte, []int) {
	return file_rebac_v1_check_proto_rawDescGZIP(), []int{1, 0}
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object   *ObjectReference  `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Relation string            `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject  *SubjectReference `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rebac_v1_check_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rebac_v1_check_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_rebac_v1_check_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetObject() *ObjectReference {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed CheckResponse_Allowed `protobuf:"varint,1,opt,name=allowed,proto3,enum=api.rebac.v1.CheckResponse_Allowed" json:"allowed,omitempty"`
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rebac_v1_check_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rebac_v1_check_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_rebac_v1_check_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() CheckResponse_Allowed {
	if x != nil {
		return x.Allowed
	}
	return CheckResponse_ALLOWED_UNSPECIFIED
}

var File_rebac_v1_check_proto protoreflect.FileDescriptor

var file_rebac_v1_check_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x62, 0x61,
	0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x72, 0x65, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9b, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x35, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x62, 0x61,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x97,
	0x01, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x22,
	0x47, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x4c,
	0x4c, 0x4f, 0x57, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x44, 0x5f, 0x54,
	0x52, 0x55, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x44,
	0x5f, 0x46, 0x41, 0x4c, 0x53, 0x45, 0x10, 0x02, 0x32, 0x5f, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x12, 0x56, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x65, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x62,
	0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a, 0x01, 0x2a, 0x22, 0x09,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x2c, 0x0a, 0x0c, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x65, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1a, 0x63, 0x69, 0x61,
	0x6d, 0x2d, 0x72, 0x65, 0x62, 0x61, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x62, 0x61,
	0x63, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rebac_v1_check_proto_rawDescOnce sync.Once
	file_rebac_v1_check_proto_rawDescData = file_rebac_v1_check_proto_rawDesc
)

func file_rebac_v1_check_proto_rawDescGZIP() []byte {
	file_rebac_v1_check_proto_rawDescOnce.Do(func() {
		file_rebac_v1_check_proto_rawDescData = protoimpl.X.CompressGZIP(file_rebac_v1_check_proto_rawDescData)
	})
	return file_rebac_v1_check_proto_rawDescData
}

var file_rebac_v1_check_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rebac_v1_check_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rebac_v1_check_proto_goTypes = []interface{}{
	(CheckResponse_Allowed)(0), // 0: api.rebac.v1.CheckResponse.Allowed
	(*CheckRequest)(nil),       // 1: api.rebac.v1.CheckRequest
	(*CheckResponse)(nil),      // 2: api.rebac.v1.CheckResponse
	(*ObjectReference)(nil),    // 3: api.rebac.v1.ObjectReference
	(*SubjectReference)(nil),   // 4: api.rebac.v1.SubjectReference
}
var file_rebac_v1_check_proto_depIdxs = []int32{
	3, // 0: api.rebac.v1.CheckRequest.object:type_name -> api.rebac.v1.ObjectReference
	4, // 1: api.rebac.v1.CheckRequest.subject:type_name -> api.rebac.v1.SubjectReference
	0, // 2: api.rebac.v1.CheckResponse.allowed:type_name -> api.rebac.v1.CheckResponse.Allowed
	1, // 3: api.rebac.v1.Check.Check:input_type -> api.rebac.v1.CheckRequest
	2, // 4: api.rebac.v1.Check.Check:output_type -> api.rebac.v1.CheckResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rebac_v1_check_proto_init() }
func file_rebac_v1_check_proto_init() {
	if File_rebac_v1_check_proto != nil {
		return
	}
	file_rebac_v1_relationships_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rebac_v1_check_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rebac_v1_check_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rebac_v1_check_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rebac_v1_check_proto_goTypes,
		DependencyIndexes: file_rebac_v1_check_proto_depIdxs,
		EnumInfos:         file_rebac_v1_check_proto_enumTypes,
		MessageInfos:      file_rebac_v1_check_proto_msgTypes,
	}.Build()
	File_rebac_v1_check_proto = out.File
	file_rebac_v1_check_proto_rawDesc = nil
	file_rebac_v1_check_proto_goTypes = nil
	file_rebac_v1_check_proto_depIdxs = nil
}
