// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v3.21.12
// source: health/v1/health.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHealthGetLivez = "/api.health.v1.Health/GetLivez"
const OperationHealthGetReadyz = "/api.health.v1.Health/GetReadyz"

type HealthHTTPServer interface {
	GetLivez(context.Context, *GetLivezRequest) (*GetLivezReply, error)
	GetReadyz(context.Context, *GetReadyzRequest) (*GetReadyzReply, error)
}

func RegisterHealthHTTPServer(s *http.Server, srv HealthHTTPServer) {
	r := s.Route("/")
	r.GET("/livez", _Health_GetLivez0_HTTP_Handler(srv))
	r.GET("/readyz", _Health_GetReadyz0_HTTP_Handler(srv))
}

func _Health_GetLivez0_HTTP_Handler(srv HealthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLivezRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthGetLivez)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLivez(ctx, req.(*GetLivezRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLivezReply)
		return ctx.Result(200, reply)
	}
}

func _Health_GetReadyz0_HTTP_Handler(srv HealthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReadyzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthGetReadyz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReadyz(ctx, req.(*GetReadyzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReadyzReply)
		return ctx.Result(200, reply)
	}
}

type HealthHTTPClient interface {
	GetLivez(ctx context.Context, req *GetLivezRequest, opts ...http.CallOption) (rsp *GetLivezReply, err error)
	GetReadyz(ctx context.Context, req *GetReadyzRequest, opts ...http.CallOption) (rsp *GetReadyzReply, err error)
}

type HealthHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthHTTPClient(client *http.Client) HealthHTTPClient {
	return &HealthHTTPClientImpl{client}
}

func (c *HealthHTTPClientImpl) GetLivez(ctx context.Context, in *GetLivezRequest, opts ...http.CallOption) (*GetLivezReply, error) {
	var out GetLivezReply
	pattern := "/livez"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthGetLivez))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HealthHTTPClientImpl) GetReadyz(ctx context.Context, in *GetReadyzRequest, opts ...http.CallOption) (*GetReadyzReply, error) {
	var out GetReadyzReply
	pattern := "/readyz"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthGetReadyz))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
