// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.1
// source: health/v1/health.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	KesselHealth_GetLivez_FullMethodName  = "/kessel.relations.v1.KesselHealth/GetLivez"
	KesselHealth_GetReadyz_FullMethodName = "/kessel.relations.v1.KesselHealth/GetReadyz"
)

// KesselHealthClient is the client API for KesselHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KesselHealthClient interface {
	GetLivez(ctx context.Context, in *GetLivezRequest, opts ...grpc.CallOption) (*GetLivezReply, error)
	GetReadyz(ctx context.Context, in *GetReadyzRequest, opts ...grpc.CallOption) (*GetReadyzReply, error)
}

type kesselHealthClient struct {
	cc grpc.ClientConnInterface
}

func NewKesselHealthClient(cc grpc.ClientConnInterface) KesselHealthClient {
	return &kesselHealthClient{cc}
}

func (c *kesselHealthClient) GetLivez(ctx context.Context, in *GetLivezRequest, opts ...grpc.CallOption) (*GetLivezReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLivezReply)
	err := c.cc.Invoke(ctx, KesselHealth_GetLivez_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kesselHealthClient) GetReadyz(ctx context.Context, in *GetReadyzRequest, opts ...grpc.CallOption) (*GetReadyzReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadyzReply)
	err := c.cc.Invoke(ctx, KesselHealth_GetReadyz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KesselHealthServer is the server API for KesselHealth service.
// All implementations must embed UnimplementedKesselHealthServer
// for forward compatibility
type KesselHealthServer interface {
	GetLivez(context.Context, *GetLivezRequest) (*GetLivezReply, error)
	GetReadyz(context.Context, *GetReadyzRequest) (*GetReadyzReply, error)
	mustEmbedUnimplementedKesselHealthServer()
}

// UnimplementedKesselHealthServer must be embedded to have forward compatible implementations.
type UnimplementedKesselHealthServer struct {
}

func (UnimplementedKesselHealthServer) GetLivez(context.Context, *GetLivezRequest) (*GetLivezReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLivez not implemented")
}
func (UnimplementedKesselHealthServer) GetReadyz(context.Context, *GetReadyzRequest) (*GetReadyzReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReadyz not implemented")
}
func (UnimplementedKesselHealthServer) mustEmbedUnimplementedKesselHealthServer() {}

// UnsafeKesselHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KesselHealthServer will
// result in compilation errors.
type UnsafeKesselHealthServer interface {
	mustEmbedUnimplementedKesselHealthServer()
}

func RegisterKesselHealthServer(s grpc.ServiceRegistrar, srv KesselHealthServer) {
	s.RegisterService(&KesselHealth_ServiceDesc, srv)
}

func _KesselHealth_GetLivez_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLivezRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KesselHealthServer).GetLivez(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KesselHealth_GetLivez_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KesselHealthServer).GetLivez(ctx, req.(*GetLivezRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KesselHealth_GetReadyz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadyzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KesselHealthServer).GetReadyz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KesselHealth_GetReadyz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KesselHealthServer).GetReadyz(ctx, req.(*GetReadyzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KesselHealth_ServiceDesc is the grpc.ServiceDesc for KesselHealth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KesselHealth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kessel.relations.v1.KesselHealth",
	HandlerType: (*KesselHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLivez",
			Handler:    _KesselHealth_GetLivez_Handler,
		},
		{
			MethodName: "GetReadyz",
			Handler:    _KesselHealth_GetReadyz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health/v1/health.proto",
}
