name: lint deploy yaml
on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - deploy/kessel-relations-deploy.yaml
permissions:
  contents: read

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint deploy/kessel-relations-deploy.yaml -c .github/workflows/.yamllint
