name: buf-pull-request
on: pull_request
permissions:
  contents: read
jobs:
  build:
    name: Check protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: bufbuild/buf-action@v1
        with:
          format: false
          lint: true
          breaking: true
          pr_comment: false
          input: "api"
